# Generated by Django 3.2.7 on 2021-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0004_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
